// document.types.ts

// ===========================
// DOCUMENT WORKFLOW ENUMS
// ===========================

// Status of the uploaded document (for review/admin workflow)
export type DocumentStatus =
  | "pending"     // Default state - Submitted, waiting for review
  | "accepted"    // Document is good and ready for review
  | "rejected"    // Document is rejected and needs to be resubmitted
  | "requested"   // Document has been requested by chairperson
  | "rework"      // Document needs adjustment/improvement (chairperson feedback)
  | "revise";     // Document has been revised and resubmitted

// Document grouping/category
export type DocumentCategory =
  | "basic"           // Part of the standard requirements
  | "supplementary"   // Extra documents depending on study
  | "custom";         // User-added or ad-hoc docs

// ===========================
// DOCUMENT REQUIREMENTS (BLUEPRINT)
// ===========================

// Blueprint for a document requirement (used to show what needs to be uploaded)
export interface DocumentRequirement {
  id: string;               // Unique static id (e.g. "informed_consent" or a uuid for custom docs)
  title: string;            // User-facing document name
  description: string;      // What is required/expected for this document
  required: boolean;        // True if required for submission
  multiple?: boolean;       // Can user upload multiple files for this requirement?
  templateUrl?: string;     // Optional URL to a template/sample file (e.g. DOCX download)
  category: DocumentCategory; // "basic", "supplementary", or "custom"
}

// ===========================
// UPLOADED DOCUMENTS (ACTUAL FILES)
// ===========================

// Represents an actual uploaded file or set of files for a document requirement
export interface DocumentsType {
  id: string;                 // Unique document ID (generated by useDocumentIdGenerator)
  title: string;              // User-facing title (can override requirement for custom docs)
  description: string;        // Shown in admin/user UI for context
  uploadedAt: string;         // ISO timestamp string (when file was uploaded)
  fileType: string;           // MIME type (e.g. "application/pdf")
  storagePath: string;        // Firebase Storage path (where the file lives in storage)
  downloadUrl: string;        // Public download URL for the file
  category: DocumentCategory; // "basic", "supplementary", or "custom"
  status?: DocumentStatus;    // Current review status (pending/accepted/revise/rejected)
  remarks?: string;           // Reviewer/admin notes (optional)
  chairpersonComment?: string; // Chairperson's review comment
  reviewedBy?: string;        // ID of the chairperson who reviewed the document
  reviewedAt?: string;        // ISO timestamp when document was reviewed
  version: number;            // Increment if user uploads a new version of same doc
  custom?: boolean;           // True if user-added document (not from initial requirements)
  uploadedBy?: string;        // User ID of uploader (for audit trail)
  originalFileName?: string;  // Original filename before processing
  // If multiple files uploaded for a single requirement (e.g. multiple CVs)
  files?: {
    fileName: string;         // Name of the file
    fileType: string;         // MIME type
    size: number;             // Bytes
    storagePath: string;      // Firebase Storage path
    downloadUrl: string;      // Download URL
    uploadedAt: string;       // Timestamp for each file
  }[];
  // Temporary field to store File object during upload process
  _fileRef?: File;            // File object for upload (temporary, not saved to database)
}

// ===========================
// FILE MAP FOR FORMS/UPLOADERS
// ===========================

// Maps requirementId to one or more uploaded documents (useful for UI state management)
export type DocumentFileMap = {
  [requirementId: string]: DocumentsType | DocumentsType[];
};

// ===========================
// DOCUMENT REQUESTS
// ===========================

// Represents a request for additional documents from the chairperson
export interface DocumentRequest {
  id: string;                 // Unique request ID
  title: string;              // Title of the requested document
  description: string;        // Description of what's needed
  requestedBy: string;        // ID of chairperson who made the request
  requestedAt: string;        // ISO timestamp when request was made
  protocolId: string;         // Protocol this request belongs to
  urgent?: boolean;           // Whether this is an urgent request
  dueDate?: string;           // Optional due date for the document
  status: 'pending' | 'fulfilled' | 'cancelled'; // Status of the request
  fulfilledAt?: string;       // When the request was fulfilled
  fulfilledDocumentId?: string; // ID of the document that fulfilled this request
}

// ===========================
// ENHANCED DOCUMENT MANAGEMENT
// ===========================

// Document version history for tracking changes
export interface DocumentVersion {
  version: number;            // Version number (1, 2, 3, etc.)
  uploadedAt: string;         // When this version was uploaded
  uploadedBy: string;         // Who uploaded this version
  status: DocumentStatus;     // Status of this specific version
  chairpersonComment?: string; // Chairperson feedback for this version
  reviewedBy?: string;        // Who reviewed this version
  reviewedAt?: string;        // When this version was reviewed
  fileType: string;           // MIME type
  storagePath: string;        // Firebase Storage path
  downloadUrl: string;        // Download URL
  originalFileName?: string;  // Original filename
  fileSize?: number;          // File size in bytes
}

// Enhanced document interface with versioning and comprehensive status tracking
export interface EnhancedDocument {
  id: string;                 // Unique document ID
  title: string;              // Document title
  description: string;        // Document description
  category: DocumentCategory; // Document category
  currentVersion: number;      // Current version number
  currentStatus: DocumentStatus; // Current status
  uploadedBy: string;         // Who uploaded the document
  createdAt: string;           // When document was first created
  updatedAt: string;          // When document was last updated
  versions: DocumentVersion[]; // Version history
  requestId?: string;         // Associated document request ID (if applicable)
  isRequired: boolean;         // Whether this is a required document
  multiple?: boolean;          // Whether multiple files are allowed
  templateUrl?: string;       // Template URL if available
  requestMetadata?: {          // Metadata for requested documents
    urgent: boolean;
    dueDate: string | null;
    requestedAt: string;
    requestedBy: string;
  };
}

// Document request with enhanced tracking
export interface EnhancedDocumentRequest {
  id: string;                 // Unique request ID
  title: string;              // Title of the requested document
  description: string;        // Description of what's needed
  requestedBy: string;        // ID of chairperson who made the request
  requestedAt: string;        // ISO timestamp when request was made
  protocolId: string;         // Protocol this request belongs to
  urgent?: boolean;           // Whether this is an urgent request
  dueDate?: string;           // Optional due date for the document
  status: 'pending' | 'fulfilled' | 'cancelled'; // Status of the request
  fulfilledAt?: string;       // When the request was fulfilled
  fulfilledDocumentId?: string; // ID of the document that fulfilled this request
  category: DocumentCategory; // Category of the requested document
  isRequired: boolean;        // Whether this is a required document
  multiple?: boolean;         // Whether multiple files are allowed
  templateUrl?: string;       // Template URL if available
}
